# Generated by Django 5.1 on 2024-09-03 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_material_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
